
    ## V2

    if [[ -f "`getconfigdir`/nougat" ]]
    then

        mv "`getconfigdir`/nougat" "`getconfigdir`/nougat.old"

        source "`getconfigdir`/nougat.old"

        cat >> "${configfile}" << EOF
## AUTOGENERATED CONFIG - NOUGAT V3 - PORTED FROM NOUGAT V2 CONFIG
SCREENSHOT_DIRECTORY="${NOUGAT_SCREENSHOT_DIRECTORY}"
ORGANIZATION_POLICY="${NOUGAT_ORGANIZATION_POLICY}"
NOUGAT_LINKING_POLICY="${NOUGAT_LINKING_POLICY}"
EOF

    ## V1

    elif [[ -n "${NOUGAT_SCREENSHOT_DIRECTORY}" ]]
    then

        cat >> "${configfile}" << EOF
## AUTOGENERATED CONFIG - NOUGAT V3 - PORTED FROM NOUGAT V1 CONFIG
SCREENSHOT_DIRECTORY="${NOUGAT_SCREENSHOT_DIRECTORY}"
EOF

    else

        mkdir -p "`getconfigdir`/nougat/"

        cat >> "${configfile}" << EOF
## AUTOGENERATED CONFIG - NOUGAT V3
SELECTION_METHOD="default"
SCREENSHOT_DIRECTORY="\$HOME/Pictures/Screenshots"
SCREENCAST_DIRECTORY="\$HOME/Videos/Screencasts"
ORGANIZATION_POLICY='\${year}/\${month}/\${day}/\${hour}:\${minute}:\${second}'
EOF

    fi

    source "${configfile}"
