SELECTION_METHOD="${SELECTION_METHOD:-default}"

SCREENSHOT_DIRECTORY="${SCREENSHOT_DIRECTORY:-$HOME/Pictures/Screenshots}"
SCREENCAST_DIRECTORY="${SCREENCAST_DIRECTORY:-$HOME/Videos/Screencasts}"

DEFAULT_POLICY='${year}/${month}/${day}/${hour}:${minute}:${second}'
ORGANIZATION_POLICY="${ORGANIZATION_POLICY:-$DEFAULT_POLICY}"
LINKING_POLICY="${LINKING_POLICY}"
